import { DatabaseSync } from 'node:sqlite'

import { describe, expect, it } from 'vitest'

import { formatSql } from '@/utils/formatters'
import {
  convertSqlDialect,
  getSqlFormatterDialect,
  SQL_DIALECT_OPTIONS,
  type SqlDatabaseDialect,
} from '@/utils/sqlDialectConverter'

const dialects = SQL_DIALECT_OPTIONS.map((option) => option.value)

const sourceQueries: Record<SqlDatabaseDialect, string> = {
  standard: `SELECT COALESCE("name", '') FROM "users" ORDER BY "id" OFFSET 1 ROWS FETCH FIRST 3 ROWS ONLY;`,
  mysql: "SELECT IFNULL(`name`, '') FROM `users` ORDER BY `id` LIMIT 3 OFFSET 1;",
  mariadb: "SELECT IFNULL(`name`, '') FROM `users` ORDER BY `id` LIMIT 3 OFFSET 1;",
  postgresql: `SELECT COALESCE("name", '') FROM "users" ORDER BY "id" LIMIT 3 OFFSET 1;`,
  oracle: `SELECT NVL("name", '') FROM "users" ORDER BY "id" OFFSET 1 ROWS FETCH FIRST 3 ROWS ONLY;`,
  sqlserver: "SELECT TOP (3) ISNULL([name], '') FROM [users] ORDER BY [id];",
  sqlite: `SELECT IFNULL("name", '') FROM "users" ORDER BY "id" LIMIT 3 OFFSET 1;`,
}

const queryPairs = dialects.flatMap((source) => dialects
  .filter((target) => target !== source)
  .map((target) => ({ source, target })))

function quotedIdentifier(value: string, target: SqlDatabaseDialect): string {
  if (target === 'mysql' || target === 'mariadb') return `\`${value}\``
  if (target === 'sqlserver') return `[${value}]`
  return `"${value}"`
}

function expectTargetPagination(sql: string, source: SqlDatabaseDialect, target: SqlDatabaseDialect): void {
  if (target === 'sqlserver') {
    expect(sql).toMatch(/OFFSET 1 ROWS FETCH NEXT 3 ROWS ONLY/i)
    expect(sql).not.toMatch(/\bLIMIT\b|FETCH FIRST/i)
    return
  }
  if (target === 'standard' || target === 'oracle') {
    expect(sql).toMatch(source === 'sqlserver'
      ? /FETCH FIRST 3 ROWS ONLY/i
      : /OFFSET 1 ROWS FETCH FIRST 3 ROWS ONLY/i)
    expect(sql).not.toMatch(/\bLIMIT\b|\bTOP\b/i)
    return
  }
  expect(sql).toMatch(source === 'sqlserver' ? /LIMIT 3\b/i : /LIMIT 3 OFFSET 1/i)
  expect(sql).not.toMatch(/\bTOP\b|FETCH FIRST/i)
}

function expectTargetNullFunction(sql: string, target: SqlDatabaseDialect): void {
  const accepted: Record<SqlDatabaseDialect, string[]> = {
    standard: ['COALESCE'],
    mysql: ['COALESCE', 'IFNULL'],
    mariadb: ['COALESCE', 'IFNULL'],
    postgresql: ['COALESCE'],
    oracle: ['COALESCE', 'NVL'],
    sqlserver: ['COALESCE', 'ISNULL'],
    sqlite: ['COALESCE', 'IFNULL'],
  }
  expect(accepted[target].some((name) => sql.toUpperCase().includes(`${name}(`))).toBe(true)
}

describe('SQL dialect pair matrix', () => {
  it('keeps the supported database catalog and formatter mapping complete', () => {
    expect(dialects).toEqual(['standard', 'mysql', 'mariadb', 'postgresql', 'oracle', 'sqlserver', 'sqlite'])
    for (const dialect of dialects) expect(getSqlFormatterDialect(dialect)).toBeTruthy()
  })

  it.each(queryPairs)('converts a representative query from $source to $target', ({ source, target }) => {
    const result = convertSqlDialect(sourceQueries[source], source, target)

    expect(result.sql).toContain(quotedIdentifier('name', target))
    expect(result.sql).toContain(quotedIdentifier('users', target))
    expect(result.sql).not.toContain('undefined')
    expectTargetNullFunction(result.sql, target)
    expectTargetPagination(result.sql, source, target)
    expect(() => formatSql(result.sql, getSqlFormatterDialect(target), 'upper', 2)).not.toThrow()
  })
})

describe('SQL dialect DDL matrix', () => {
  it.each([
    {
      label: 'MySQL to Oracle',
      source: 'mysql' as const,
      target: 'oracle' as const,
      sql: 'CREATE TABLE `users` (id BIGINT AUTO_INCREMENT PRIMARY KEY, enabled TINYINT(1), payload LONGBLOB, created_at DATETIME);',
      patterns: [
        /CREATE TABLE "users"/i,
        /id NUMBER\(19\)\s+GENERATED BY DEFAULT AS IDENTITY\s+PRIMARY KEY/i,
        /enabled NUMBER\(1\)/i,
        /payload BLOB/i,
        /created_at TIMESTAMP/i,
      ],
    },
    {
      label: 'MariaDB to SQL Server',
      source: 'mariadb' as const,
      target: 'sqlserver' as const,
      sql: 'CREATE TABLE `users` (id BIGINT AUTO_INCREMENT PRIMARY KEY, enabled TINYINT(1), payload LONGBLOB, created_at DATETIME);',
      patterns: [
        /CREATE TABLE \[users\]/i,
        /id BIGINT\s+IDENTITY\(1,1\)\s+PRIMARY KEY/i,
        /enabled BIT/i,
        /payload VARBINARY\(MAX\)/i,
        /created_at DATETIME2/i,
      ],
    },
    {
      label: 'PostgreSQL to MySQL',
      source: 'postgresql' as const,
      target: 'mysql' as const,
      sql: 'CREATE TABLE "users" (id BIGSERIAL PRIMARY KEY, enabled BOOLEAN, uid UUID, payload BYTEA, created_at TIMESTAMP);',
      patterns: [
        /CREATE TABLE `users`/i,
        /id BIGINT AUTO_INCREMENT\s+PRIMARY KEY/i,
        /enabled TINYINT\(1\)/i,
        /uid CHAR\(36\)/i,
        /payload LONGBLOB/i,
      ],
    },
    {
      label: 'Oracle to PostgreSQL',
      source: 'oracle' as const,
      target: 'postgresql' as const,
      sql: 'CREATE TABLE "users" (id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR2(80), note CLOB, payload RAW(16));',
      patterns: [
        /id DECIMAL\(19\)\s+GENERATED BY DEFAULT AS IDENTITY\s+PRIMARY KEY/i,
        /name VARCHAR\(80\)/i,
        /note TEXT/i,
        /payload BYTEA/i,
      ],
    },
    {
      label: 'SQL Server to SQLite',
      source: 'sqlserver' as const,
      target: 'sqlite' as const,
      sql: 'CREATE TABLE [users] ([id] BIGINT IDENTITY(1,1) PRIMARY KEY, [enabled] BIT, [note] NVARCHAR(MAX), [payload] VARBINARY(MAX), [created_at] DATETIME2);',
      patterns: [
        /"id" INTEGER\s+PRIMARY KEY AUTOINCREMENT/i,
        /"enabled" INTEGER/i,
        /"note" TEXT/i,
        /"payload" BLOB/i,
        /"created_at" TEXT/i,
      ],
    },
    {
      label: 'SQLite to Oracle',
      source: 'sqlite' as const,
      target: 'oracle' as const,
      sql: 'CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "note" TEXT, "payload" BLOB, "enabled" BOOLEAN);',
      patterns: [
        /"id" NUMBER\(10\)\s+GENERATED BY DEFAULT AS IDENTITY\s+PRIMARY KEY/i,
        /"note" CLOB/i,
        /"payload" BLOB/i,
        /"enabled" NUMBER\(1\)/i,
      ],
    },
    {
      label: 'standard SQL to MariaDB',
      source: 'standard' as const,
      target: 'mariadb' as const,
      sql: 'CREATE TABLE "users" ("id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, "enabled" BOOLEAN, "name" VARCHAR(80), "payload" BLOB);',
      patterns: [
        /`id` BIGINT\s+AUTO_INCREMENT\s+PRIMARY KEY/i,
        /`enabled` TINYINT\(1\)/i,
        /`name` VARCHAR\(80\)/i,
        /`payload` LONGBLOB/i,
      ],
    },
  ])('$label maps common column types and identity syntax', ({ source, target, sql, patterns }) => {
    const result = convertSqlDialect(sql, source, target)
    for (const pattern of patterns) expect(result.sql).toMatch(pattern)
    expect(result.changes.some((change) => change.startsWith('数据类型'))).toBe(true)
    if (!(source === 'oracle' && target === 'postgresql')) {
      expect(result.changes.some((change) => change.startsWith('自增语法'))).toBe(true)
    }
    expect(() => formatSql(result.sql, getSqlFormatterDialect(target), 'upper', 2)).not.toThrow()
  })

  it.each([
    {
      source: 'mysql' as const,
      table: 'mysql_users',
      sql: 'CREATE TABLE mysql_users (id BIGINT AUTO_INCREMENT PRIMARY KEY, enabled TINYINT(1), note LONGTEXT);',
    },
    {
      source: 'sqlserver' as const,
      table: 'sqlserver_users',
      sql: 'CREATE TABLE sqlserver_users (id BIGINT IDENTITY(1,1) PRIMARY KEY, enabled BIT, payload VARBINARY(MAX));',
    },
    {
      source: 'standard' as const,
      table: 'standard_users',
      sql: 'CREATE TABLE standard_users (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, enabled BOOLEAN);',
    },
  ])('executes $source identity DDL after conversion to SQLite', ({ source, table, sql }) => {
    const converted = convertSqlDialect(sql, source, 'sqlite')
    const database = new DatabaseSync(':memory:')
    try {
      database.exec(converted.sql)
      database.exec(`INSERT INTO ${table} DEFAULT VALUES`)
      expect(database.prepare(`SELECT id FROM ${table}`).get()).toMatchObject({ id: 1 })
    } finally {
      database.close()
    }
  })

  it('does not invent a SQLite primary key when the source identity column has none', () => {
    const result = convertSqlDialect('CREATE TABLE audit (id BIGINT AUTO_INCREMENT);', 'mysql', 'sqlite')
    expect(result.sql).toMatch(/id INTEGER\s*\)/i)
    expect(result.sql).not.toContain('AUTOINCREMENT')
    expect(result.warnings).toContain('SQLite 自增列必须同时是 INTEGER PRIMARY KEY；未自动增加主键约束')
  })

  it('maps types inside CAST expressions', () => {
    expect(convertSqlDialect('SELECT CAST(payload AS BYTEA) FROM events', 'postgresql', 'sqlserver').sql)
      .toContain('CAST(payload AS VARBINARY(MAX))')
    expect(convertSqlDialect('SELECT CAST(enabled AS BIT) FROM events', 'sqlserver', 'postgresql').sql)
      .toContain('CAST(enabled AS BOOLEAN)')
  })
})

describe('SQL dialect functions, parameters and safety warnings', () => {
  it.each([
    {
      source: 'mysql' as const,
      target: 'sqlserver' as const,
      sql: 'SELECT IFNULL(LENGTH(SUBSTR(name, 1, 2)), 0), NOW() FROM users',
      expected: ['ISNULL(', 'LEN(', 'SUBSTRING(', 'CURRENT_TIMESTAMP'],
    },
    {
      source: 'oracle' as const,
      target: 'postgresql' as const,
      sql: 'SELECT NVL(LENGTH(SUBSTR(name, 1, 2)), 0), SYSDATE FROM users',
      expected: ['COALESCE(', 'LENGTH(', 'SUBSTRING(', 'CURRENT_TIMESTAMP'],
    },
    {
      source: 'sqlserver' as const,
      target: 'oracle' as const,
      sql: 'SELECT ISNULL(LEN(SUBSTRING(name, 1, 2)), 0), GETDATE() FROM users',
      expected: ['NVL(', 'LENGTH(', 'SUBSTR(', 'CURRENT_TIMESTAMP'],
    },
    {
      source: 'sqlite' as const,
      target: 'sqlserver' as const,
      sql: 'SELECT IFNULL(LENGTH(SUBSTR(name, 1, 2)), 0), CURRENT_TIMESTAMP FROM users',
      expected: ['ISNULL(', 'LEN(', 'SUBSTRING(', 'CURRENT_TIMESTAMP'],
    },
  ])('maps common functions from $source to $target', ({ source, target, sql, expected }) => {
    const result = convertSqlDialect(sql, source, target)
    for (const fragment of expected) expect(result.sql).toContain(fragment)
  })

  it.each([
    {
      source: 'mysql' as const,
      target: 'oracle' as const,
      sql: 'SELECT id FROM users LIMIT ?, ?',
      expected: /OFFSET \? ROWS FETCH FIRST \? ROWS ONLY/i,
    },
    {
      source: 'postgresql' as const,
      target: 'sqlserver' as const,
      sql: 'SELECT id FROM users ORDER BY id LIMIT $1 OFFSET $2',
      expected: /OFFSET \$2 ROWS FETCH NEXT \$1 ROWS ONLY/i,
    },
    {
      source: 'oracle' as const,
      target: 'mysql' as const,
      sql: 'SELECT id FROM users OFFSET :offset ROWS FETCH FIRST :limit ROWS ONLY',
      expected: /LIMIT :limit OFFSET :offset/i,
    },
    {
      source: 'sqlserver' as const,
      target: 'postgresql' as const,
      sql: 'SELECT TOP (@take) id FROM users',
      expected: /LIMIT @take/i,
    },
  ])('preserves parameterized pagination from $source for $target with a binding warning', ({ source, target, sql, expected }) => {
    const result = convertSqlDialect(sql, source, target)
    expect(result.sql).toMatch(expected)
    expect(result.warnings).toContain('参数占位符由驱动或框架决定，已原样保留，请按目标客户端绑定语法复核')
  })

  it('converts multiple statements independently', () => {
    const result = convertSqlDialect('SELECT TOP 2 id FROM a; SELECT TOP 4 id FROM b;', 'sqlserver', 'postgresql')
    expect(result.sql).toMatch(/FROM a LIMIT 2;/i)
    expect(result.sql).toMatch(/FROM b LIMIT 4;/i)
    expect(result.changes).toContain('分页语法 x2')
  })

  it('protects comments, strings and escaped identifiers from rewrites', () => {
    const mysql = convertSqlDialect("SELECT IFNULL(`a``b`, 'NVL(x) LIMIT 1') FROM `t` # LIMIT 99", 'mysql', 'oracle')
    expect(mysql.sql).toContain('NVL("a`b"')
    expect(mysql.sql).toContain("'NVL(x) LIMIT 1'")
    expect(mysql.sql).toContain('# LIMIT 99')

    const sqlserver = convertSqlDialect('SELECT [a]]b] FROM [t] /* TOP 1 /* LIMIT 2 */ NVL(x) */', 'sqlserver', 'mysql')
    expect(sqlserver.sql).toContain('`a]b`')
    expect(sqlserver.sql).toContain('/* TOP 1 /* LIMIT 2 */ NVL(x) */')
  })

  it.each([
    ['oracle', 'mysql', 'SELECT * FROM employees START WITH manager_id IS NULL CONNECT BY PRIOR id = manager_id', 'Oracle CONNECT BY 未自动改写为递归 CTE'],
    ['mysql', 'oracle', 'INSERT INTO users(id) VALUES (1) ON DUPLICATE KEY UPDATE id = 1', 'ON DUPLICATE KEY 未自动迁移为目标数据库 UPSERT'],
    ['postgresql', 'mysql', 'INSERT INTO users(id) VALUES (1) ON CONFLICT(id) DO NOTHING', 'ON CONFLICT 未自动迁移为目标数据库 UPSERT'],
    ['sqlserver', 'oracle', 'UPDATE users SET enabled = 1 OUTPUT inserted.id', 'SQL Server OUTPUT 子句未自动迁移'],
    ['standard', 'sqlite', 'MERGE INTO users u USING incoming i ON (u.id = i.id) WHEN MATCHED THEN UPDATE SET u.name = i.name', '各数据库 MERGE 语义差异较大，请人工验证匹配与并发行为'],
    ['sqlserver', 'postgresql', 'SELECT 1\nGO\nSELECT 2', '脚本批次分隔符未转换，请按目标客户端要求调整'],
    ['postgresql', 'mysql', "SELECT first_name || last_name FROM users", '字符串连接运算符的 NULL 与 SQL 模式语义不同，未自动改写'],
  ] as Array<[SqlDatabaseDialect, SqlDatabaseDialect, string, string]>)('warns for unsafe %s constructs when targeting %s', (source, target, sql, warning) => {
    expect(convertSqlDialect(sql, source, target).warnings).toContain(warning)
  })
})
