import { describe, expect, it } from 'vitest'

import { formatSql } from '@/utils/formatters'
import {
  convertSqlDialect,
  getSqlFormatterDialect,
  normalizeSqlDatabaseDialect,
} from '@/utils/sqlDialectConverter'

describe('SQL dialect conversion', () => {
  it('exposes Oracle as a first-class dialect while migrating the old PL/SQL setting', () => {
    expect(normalizeSqlDatabaseDialect('plsql')).toBe('oracle')
    expect(getSqlFormatterDialect('oracle')).toBe('plsql')
    expect(formatSql('select nvl(name, \'\') from users', getSqlFormatterDialect('oracle'), 'upper', 2)).toContain('SELECT')
  })

  it('converts MySQL identifiers, functions and pagination to Oracle', () => {
    const result = convertSqlDialect(
      "select `user_id`, ifnull(name, 'LIMIT 1') from `users` limit 5, 10",
      'mysql',
      'oracle',
    )

    expect(result.sql).toContain('select "user_id", NVL(name')
    expect(result.sql).toContain("'LIMIT 1'")
    expect(result.sql).toContain('from "users" OFFSET 5 ROWS FETCH FIRST 10 ROWS ONLY')
    expect(result.changes).toEqual(expect.arrayContaining(['标识符引号 x2', '内置函数', '分页语法']))
  })

  it('converts SQL Server TOP syntax and built-ins to MySQL', () => {
    const result = convertSqlDialect(
      'SELECT DISTINCT TOP (20) [id], ISNULL([name], \'\'), GETDATE() FROM [users];',
      'sqlserver',
      'mysql',
    )

    expect(result.sql).toContain('SELECT DISTINCT  `id`, IFNULL(`name`, \'\'), CURRENT_TIMESTAMP FROM `users` LIMIT 20;')
    expect(result.changes).toEqual(expect.arrayContaining(['标识符引号 x3', '内置函数', '当前时间函数', '分页语法']))
  })

  it('keeps SQL Server temporary table names instead of treating them as MySQL comments', () => {
    const result = convertSqlDialect('SELECT TOP 1 * FROM #recent_users', 'sqlserver', 'postgresql')

    expect(result.sql).toContain('FROM #recent_users LIMIT 1')
  })

  it('warns when MySQL double quotes depend on ANSI_QUOTES mode', () => {
    const result = convertSqlDialect('SELECT "display_name" FROM users', 'mysql', 'sqlserver')

    expect(result.warnings).toContain('MySQL 双引号受 ANSI_QUOTES 模式影响，当前按标识符处理，请确认原 SQL 模式')
  })

  it('converts common MySQL DDL types and identity syntax to PostgreSQL', () => {
    const result = convertSqlDialect(
      'CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY, active TINYINT(1), payload LONGTEXT);',
      'mysql',
      'postgresql',
    )

    expect(result.sql).toContain('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    expect(result.sql).toContain('active BOOLEAN')
    expect(result.sql).toContain('payload TEXT')
    expect(result.changes).toEqual(expect.arrayContaining(['数据类型 x2', '自增语法']))
  })

  it('maps common integer widths when converting DDL to Oracle', () => {
    const result = convertSqlDialect(
      'CREATE TABLE counters (small_value SMALLINT, normal_value INT, large_value BIGINT);',
      'postgresql',
      'oracle',
    )

    expect(result.sql).toContain('small_value NUMBER(5)')
    expect(result.sql).toContain('normal_value NUMBER(10)')
    expect(result.sql).toContain('large_value NUMBER(19)')
  })

  it('converts PostgreSQL DOUBLE PRECISION without leaving a dangling type keyword', () => {
    const result = convertSqlDialect('CREATE TABLE metrics (value DOUBLE PRECISION);', 'postgresql', 'oracle')

    expect(result.sql).toContain('value BINARY_DOUBLE')
    expect(result.sql).not.toContain('BINARY_DOUBLE PRECISION')
  })

  it('adds the SQL Server ordering safeguard when converting offset pagination', () => {
    const result = convertSqlDialect('SELECT id FROM users LIMIT 10 OFFSET 5', 'postgresql', 'sqlserver')

    expect(result.sql).toContain('ORDER BY (SELECT NULL) OFFSET 5 ROWS FETCH NEXT 10 ROWS ONLY')
    expect(result.warnings).toContain('SQL Server OFFSET 必须包含 ORDER BY；已补占位排序，请替换为稳定排序列')
  })

  it('converts pagination in nested queries independently', () => {
    const result = convertSqlDialect(
      'SELECT * FROM (SELECT id FROM users ORDER BY id LIMIT 5) recent ORDER BY id LIMIT 10',
      'postgresql',
      'oracle',
    )

    expect(result.sql).toMatch(/ORDER BY id FETCH FIRST 5 ROWS ONLY\s*\) recent/)
    expect(result.sql).toContain('ORDER BY id FETCH FIRST 10 ROWS ONLY')
    expect(result.changes).toContain('分页语法 x2')
  })

  it('uses valid target syntax for offset-only queries', () => {
    expect(convertSqlDialect('SELECT id FROM users OFFSET 5 ROWS', 'oracle', 'postgresql').sql).toContain('OFFSET 5')
    expect(convertSqlDialect('SELECT id FROM users OFFSET 5 ROWS', 'oracle', 'sqlite').sql).toContain('LIMIT -1 OFFSET 5')
    expect(convertSqlDialect('SELECT id FROM users OFFSET 5 ROWS', 'oracle', 'mysql').sql).toContain('LIMIT 18446744073709551615 OFFSET 5')
  })

  it('removes PostgreSQL LIMIT ALL and preserves an accompanying offset', () => {
    const result = convertSqlDialect('SELECT id FROM users LIMIT ALL OFFSET 5', 'postgresql', 'oracle')

    expect(result.sql).toContain('OFFSET 5 ROWS')
    expect(result.sql).not.toContain('ALL')
  })

  it('preserves strings and comments while reporting constructs that need manual migration', () => {
    const result = convertSqlDialect(
      "SELECT 'NVL(x) LIMIT 1' AS note, created_at::DATE FROM users -- LIMIT 99\nWHERE name ILIKE 'kai%'",
      'postgresql',
      'oracle',
    )

    expect(result.sql).toContain("'NVL(x) LIMIT 1'")
    expect(result.sql).toContain('-- LIMIT 99')
    expect(result.sql).toContain('created_at::DATE')
    expect(result.warnings).toEqual(expect.arrayContaining([
      'ILIKE 的大小写语义依赖排序规则，未自动改写',
      'PostgreSQL :: 类型转换未自动改写，请改用 CAST',
    ]))
  })

  it('protects PostgreSQL dollar-quoted bodies and reports Oracle ROWNUM semantics', () => {
    const body = "CREATE FUNCTION demo() RETURNS text AS $$ BEGIN RETURN 'LIMIT 1 NVL(x)'; END $$ LANGUAGE plpgsql;"
    const postgresResult = convertSqlDialect(body, 'postgresql', 'oracle')
    expect(postgresResult.sql).toContain("$$ BEGIN RETURN 'LIMIT 1 NVL(x)'; END $$")

    const oracleResult = convertSqlDialect('SELECT * FROM users WHERE ROWNUM <= 10', 'oracle', 'mysql')
    expect(oracleResult.warnings).toContain('Oracle ROWNUM 的取数顺序语义未自动改写，请按目标数据库分页或窗口函数复核')
  })

  it('only formats when source and target dialects are the same', () => {
    const sql = 'select * from users limit 10'
    expect(convertSqlDialect(sql, 'mysql', 'mysql')).toEqual({ sql, changes: [], warnings: [] })
  })
})
